languages:
  JavaScript: true
ratings:
  paths:
  - "js/compiler/*"
  - "js/vm/*"
exclude_paths:
  - css/*
  - site/*
  - fonts/*
  - ev3/*
  - node_modules/*
  - test/*
  - whl/*
  - js/simulator/*.js
  - js/simulator/**/*
