wheel(
    'simulator.includes.standard',
    [
        '#define MODULE_SCREEN         1',
        '',
        '#define MODULE_STANDARD       0',
        '',
        '#define STANDARD_PRINT_NUMBER 0',
        '#define STANDARD_PRINT_STRING 1',
        '#define STANDARD_SLEEP        2',
        '',
        '#define TRUE                  1',
        '#define FALSE                 0',
        '',
        'proc printN(number n)',
        '    record PrintNumber',
        '        number   n',
        '    endr',
        '    PrintNumber printNumber',
        '    set      printNumber.n,          n',
        '    addr     printNumber',
        '    module   MODULE_STANDARD,        STANDARD_PRINT_NUMBER',
        'endp',
        '',
        'proc printS(string s)',
        '    record PrintString',
        '        string s',
        '    endr',
        '    PrintString printString',
        '    set      printString.s,          s',
        '    addr     printString',
        '    module   MODULE_STANDARD,        STANDARD_PRINT_STRING',
        'endp',
        '',
        'proc sleep(number milliseconds)',
        '    record Sleep',
        '        number milliseconds',
        '    endr',
        '    Sleep sleep',
        '    set      sleep.milliseconds,     milliseconds',
        '    addr     sleep',
        '    module   MODULE_STANDARD,        STANDARD_SLEEP',
        'endp'
    ]
);
